openapi: 3.0.0
info:
  title: Product Catalog API
  description: API for managing product catalog
  version: 1.0.0  
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://api-staging.product-catalog.com/api/v1
    description: Staging environment
paths:
  /brands:
    post:
      summary: Create a new brand
      operationId: createBrand
      tags:
        - brands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBrandRequest'
      responses:
        '201':
          description: Brand created successfully
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: URL of the newly created brand
              example: '/api/v1/brands/1234'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandResponse'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                type: 'https://api.product-catalog.com/problems/validation-error'
                title: 'Validation Error'
                status: 400
                detail: 'The request contains invalid parameters'
                timestamp: '2024-01-20T10:30:00Z'
                path: '/api/v1/brands'
                instance: '/problems/12345'
                validationErrors: [
                  {
                    field: 'name',
                    message: 'must not be empty',
                    rejectedValue: ''
                  }
                ]
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CreateBrandRequest:
      type: object
      required:
        - name
        - website
        - logoUrl
      properties:
        name:
          type: string
          description: Brand name
          example: 'SportMaster'
          minLength: 1
          maxLength: 100
          pattern: '^[a-zA-Z0-9\s\-]+$'
        description:
          oneOf:
            - type: string
              description: Plain text description
              example: 'Leading sports equipment manufacturer'
              maxLength: 500
            - type: object
              description: Rich text description with internationalization support
              properties:
                content:
                  type: string
                  description: Description content
                  example: 'Leading sports equipment manufacturer'
                  maxLength: 500
                format:
                  type: string
                  description: Content format
                  enum: [plain, markdown, html]
                  default: plain
                  example: plain
                locale:
                  type: string
                  description: Language locale (ISO 639-1)
                  pattern: '^[a-z]{2}(-[A-Z]{2})?$'
                  example: 'en-US'
                  default: 'en'
              required:
                - content
              additionalProperties: false
        website:
          type: string
          format: uri
          description: Brand website URL
          example: 'https://sportmaster.com'
          maxLength: 255
          pattern: '^https?://.*'
        logoUrl:
          type: string
          format: uri
          description: URL to the brand logo image (absolute URL or relative path)
          example: 'sportmaster-logo.png'
          maxLength: 255
          pattern: '^(https?://.*|[^/].*)'
      additionalProperties: false

    BrandResponse:
      type: object
      required:
        - id
        - name
        - website
        - logoUrl
        - createdAt
        - updatedAt
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the brand
          example: 1234
        name:
          type: string
          description: Brand name
          example: 'SportMaster'
          maxLength: 100
        description:
          oneOf:
            - type: string
              description: Plain text description
              example: 'Leading sports equipment manufacturer'
              maxLength: 500
            - type: object
              description: Rich text description with internationalization support
              properties:
                content:
                  type: string
                  description: Description content
                  example: 'Leading sports equipment manufacturer'
                  maxLength: 500
                format:
                  type: string
                  description: Content format
                  enum: [plain, markdown, html]
                  default: plain
                  example: plain
                locale:
                  type: string
                  description: Language locale (ISO 639-1)
                  pattern: '^[a-z]{2}(-[A-Z]{2})?$'
                  example: 'en-US'
                  default: 'en'
              required:
                - content
              additionalProperties: false
        website:
          type: string
          format: uri
          description: Brand website URL
          example: 'https://sportmaster.com'
          maxLength: 255          
        logoUrl:
          type: string
          format: uri
          description: URL to the brand logo image (absolute URL or relative path)
          example: 'sportmaster-logo.png'
          maxLength: 255
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: '2023-06-07T14:30:00Z'
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: '2023-06-07T14:30:00Z'

    ErrorResponse:
      type: object
      description: Problem Details for HTTP APIs (RFC 7807)
      required:
        - type
        - title
        - status
        - detail
        - timestamp
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type
          format: uri
          example: 'https://api.product-catalog.com/problems/validation-error'
        title:
          type: string
          description: A short, human-readable summary of the problem type
          example: 'Validation Error'
          maxLength: 100
        status:
          type: integer
          description: The HTTP status code
          minimum: 100
          maximum: 599
          example: 400
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
          example: 'Brand name must not be empty and must be less than 100 characters'
          maxLength: 500
        timestamp:
          type: string
          format: date-time
          description: The time when the error occurred
          example: '2024-01-20T10:30:00Z'
        path:
          type: string
          description: The request path that caused the error
          example: '/api/v1/brands'
          maxLength: 255
        instance:
          type: string
          description: A URI reference that identifies the specific occurrence of the problem
          format: uri
          example: '/problems/12345'
          maxLength: 255
        validationErrors:
          type: array
          description: List of field-level validation errors
          items:
            type: object
            required:
              - field
              - message
            properties:
              field:
                type: string
                description: The field that failed validation
                example: 'name'
                maxLength: 100
              message:
                type: string
                description: The validation error message
                example: 'must not be empty'
                maxLength: 200
              rejectedValue:
                type: string
                description: The value that was rejected
                example: ''
                maxLength: 500
            additionalProperties: false
      additionalProperties: false
